source 'https://github.com/CocoaPods/Specs.git'

target 'IOToastInput', :exclusive => true do
  pod "IOToastInput", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "IOToastInput", :path => "../"

  
end
